on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - run: npm install --save-dev gulp-sitemap
    - run: npm install --save-dev gulp
    - run: npm install --global gulp-cli
    - run: gulp sitemap
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.popark.it/www.popark.it/
        ftp-username: 10747798@aruba.it
        ftp-password: ${{ secrets.FTP_PASSWORD }}
